from datetime import datetime


def _clauses(terms: str) -> list[str]:
    return [item.strip() for item in terms.split(";") if item.strip()]


def generate_fallback_document(document_type: str, parties: str, terms: str, dates: str) -> str:
    clauses = _clauses(terms)
    party_lines = [p.strip() for p in parties.replace("\n", ",").split(",") if p.strip()]

    party_text = "\n".join(f"- {p}" for p in party_lines) or f"- {parties.strip()}"
    terms_text = "\n".join(
        f"{index}. {clause}" for index, clause in enumerate(clauses, start=1)
    ) or "1. The parties agree to the terms described in this document."

    title = document_type.strip().title()
    today = datetime.now().strftime("%d %B %Y")

    return f"""# {title}

**Effective Date:** {dates}

## 1. Parties
{party_text}

## 2. Purpose and Scope
This document records the understanding between the parties identified above in relation to the stated {document_type.lower()}. The parties agree to act in accordance with the terms and responsibilities set out below.

## 3. Terms and Conditions
{terms_text}

## 4. Responsibilities
Each party shall perform its responsibilities in a timely and professional manner and shall comply with the agreed terms, applicable policies, and applicable law.

## 5. Confidentiality
Where confidential information is exchanged, each party shall use reasonable care to protect that information and shall not disclose it except as permitted by the agreement or applicable law.

## 6. Term and Termination
The agreement will take effect from the Effective Date stated above. Termination, renewal, or amendment shall be handled according to the agreed terms and any applicable legal requirements.

## 7. General Provisions
Any amendment should be made in writing and accepted by the parties. If any provision is found unenforceable, the remaining provisions should continue to the extent permitted by law.

## 8. Signatures

Party 1: ______________________________

Name: ________________________________

Date: _________________________________


Party 2: ______________________________

Name: ________________________________

Date: _________________________________

---
Generated by LegalEase on {today}.
This template is AI-assisted/demonstration content and should be reviewed by a qualified legal professional before use.
"""
